name: Linting, PyLint + Black

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    branches: [ "develop", "feature/*"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black
    - name: Run PyLint
      run: |
        pylint $(git ls-files '*.py')
    - name: Run Black
      run: |
        black $(git ls-files '*.py') --check --verbose --diff --color
